# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enhanced_amr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enhanced_amr.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x65nhanced_amr.proto\":\n\x08Sentence\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07has_amr\x18\x02 \x01(\x08\x12\x0f\n\x07org_amr\x18\x03 \x01(\t\"2\n\x0c\x45nhanced_amr\x12\x0b\n\x03\x61mr\x18\x01 \x01(\t\x12\x15\n\rtopk_entities\x18\x02 \x01(\t2>\n\x0c\x41MR_Enhancer\x12.\n\x10get_enhanced_amr\x12\t.Sentence\x1a\r.Enhanced_amr\"\x00\x62\x06proto3'
)




_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Sentence.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_amr', full_name='Sentence.has_amr', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org_amr', full_name='Sentence.org_amr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=80,
)


_ENHANCED_AMR = _descriptor.Descriptor(
  name='Enhanced_amr',
  full_name='Enhanced_amr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amr', full_name='Enhanced_amr.amr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topk_entities', full_name='Enhanced_amr.topk_entities', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['Enhanced_amr'] = _ENHANCED_AMR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), {
  'DESCRIPTOR' : _SENTENCE,
  '__module__' : 'enhanced_amr_pb2'
  # @@protoc_insertion_point(class_scope:Sentence)
  })
_sym_db.RegisterMessage(Sentence)

Enhanced_amr = _reflection.GeneratedProtocolMessageType('Enhanced_amr', (_message.Message,), {
  'DESCRIPTOR' : _ENHANCED_AMR,
  '__module__' : 'enhanced_amr_pb2'
  # @@protoc_insertion_point(class_scope:Enhanced_amr)
  })
_sym_db.RegisterMessage(Enhanced_amr)



_AMR_ENHANCER = _descriptor.ServiceDescriptor(
  name='AMR_Enhancer',
  full_name='AMR_Enhancer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=134,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_enhanced_amr',
    full_name='AMR_Enhancer.get_enhanced_amr',
    index=0,
    containing_service=None,
    input_type=_SENTENCE,
    output_type=_ENHANCED_AMR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AMR_ENHANCER)

DESCRIPTOR.services_by_name['AMR_Enhancer'] = _AMR_ENHANCER

# @@protoc_insertion_point(module_scope)